### ISSUE TITLE
the streaming output not actually streaming

### ISSUE THREAD

**Issue by lucasjinreal** [matatonic/openedai-vision#11] opened 2024-08-01 04:17 UTC
using openai client to test, the client side is actually receive whole output at last, the server side can print streaming though

any reason for this?

**Comment by matatonic** [comment] 2024-08-01 04:38
Which model/backed are you using? Can you also share your client request code?

**Comment by lucasjinreal** [comment] 2024-08-01 06:13
the code like this:

```
response = client.chat.completions.create(
        model="gpt-3.5-turbo-16k",
        messages=[{"role": "user", "content": [
            {'type': 'text', 'text': '描述一下图片内容'},
            {'type': 'image_url', 'image_url': {'url': encode_image_to_base64('data/images/gt_10036.jpg')}},
            ]}],
        temperature=0.95,
        stream=True,
    )
    print_response(response)
```

it's a typical openai request.

Am used internvl2-8b model.

The phenomenon has always been reproducible stably.

**Comment by matatonic** [comment] 2024-08-01 06:49
For streamed replies you need to iterate on the response to get the streamed data, check the `chat_with_image.py` for a more detailed example, but the response should be used like this, if you want to print it:

```python
for chunk in response:
    print(chunk.choices[0].delta.content, end='', flush=True)
```

**Comment by matatonic** [comment] 2024-08-01 07:09
See also: https://platform.openai.com/docs/api-reference/streaming

**Comment by lucasjinreal** [comment] 2024-08-01 07:16
Oh, I think I miss leading you, the question is not my client, my client works well with anyother API such as openai etc.

And my `print_response` is like:

```
def print_response(response):
    if isinstance(response, openai.Stream):
        for chunk in response:
            if (
                hasattr(chunk.choices[0].delta, "content")
                and chunk.choices[0].finish_reason != "stop"
            ):
                print(chunk.choices[0].delta.content, end="", flush=True)
        print()
    else:
        print(response.choices[0].message.content)
```

I don't know if is the server issue.

**Comment by matatonic** [comment] 2024-08-01 07:26
I've just tested this for sanity sake, and OpenGVLab/InternVL2-8B streams just fine with version 0.28.1 of openedai-vision.
Can you test with `chat_with_image.py`? It would be:

```
python chat_with_image.py data/images/gt_10036.jpg "描述一下图片内容"
```

**Comment by matatonic** [comment] 2024-08-01 07:29
I wonder if the problem is "if isinstance(response, openai.Stream)", it's possible the response is not structured correctly  and may not be seen as a stream.

Update: no, I just tested, it is type: <class 'openai.Stream'>...

**Comment by matatonic** [comment] 2024-08-01 07:58
I don't know what could be wrong so far, are you using the docker image? Which client version of the python-openai code are you using?

**Comment by lucasjinreal** [comment] 2024-08-01 08:07
Thank u for the digging, the client works OK with openai's API and one of my vllm streaming server, so am afraid it was caused by some thread stuck on server.

I have encounter a similar situation where I inference with LLM in streaming, I resolve it by find I lack of a `async` in my stream prediction function.

But after I test and verify the code by yours, it's looks like flawless.

The phenomon on my side currently is:

- client can not prints output in stream, which works well with other server;
- server side I tested the function only print, it's streaming indeed one by one.

So still, I am doubt it might caused by fastapi or sse issue in asynchorinzation.

not the client, not the model generate.

**Comment by matatonic** [comment] 2024-08-01 08:13
Ugh, threading in python is a nightmare... You could try the newer AsyncClient from openai, with httpx? I don't know much about this but it seems preferred. 

See a sample here: https://github.com/openai/openai-python/blob/195c05a64d39c87b2dfdf1eca2d339597f1fce03/examples/streaming.py#L33

**Comment by matatonic** [comment] 2024-08-01 08:16
Did you confirm the code is receiving data as a stream and just printing all at once?

**Comment by matatonic** [comment] 2024-08-01 08:18
I would be interested to see the .to_json() dumps of the two different streams, so I can compare. I have built everything from reverse engineering, so I don't even test with openai API directly, just openai client. I have not ruled out a server side issue.

**Comment by lucasjinreal** [comment] 2024-08-01 08:38
> Did you confirm the code is receiving data as a stream and just printing all at once?

Let me detailed test again to answer this.

**Comment by matatonic** [comment] 2024-08-06 13:43
Any update or should I close this report?

**Comment by lucasjinreal** [comment] 2024-08-07 02:46
Hello, please wait for my debug information. Currently, I am employing non-stream directly. However, the stream functionality should be tested ultimately.

**Comment by matatonic** [comment] 2024-08-25 18:40
Hi, any update? Otherwise I think this is getting closed.

**Comment by lucasjinreal** [comment] 2024-08-26 02:25
Hi, have been busy these days. The root still not precisely investigated.

**Comment by matatonic** [comment] 2024-09-11 00:05
Hi, I'm coming back around to this again - any chance you've been able to debug it?

**Comment by matatonic** [comment] 2024-09-13 20:12
Because streaming seems to work,and I can't duplicate the issue, I'm going to close this now. Feel free to re-open a new issue, or as me to reopen this if you find some time to debug. Thanks again for the interest and your report!

**Closed as not planned by matatonic** 2024-09-13 20:12 UTC
